//* This automatically generated file is a part of Verilog testbench.
//*   This file was generated by Active-VHDL 4.1 (TB_verilog v.1.0).
//*   Copyright (C) ALDEC Inc.
//* This Verilog file contains the main Test Bench module
//* and is a part of Verilog Testbench for module "FREQUENCY_METER"
//* This file was generated on: Mon May 08 17:05:11 2000
`timescale 1ps / 1ps
module frequency_meter_tb;


//Internal signals declarations:
reg F_CONV;
reg F_INPUT;
reg F_PATTERN;
reg RESET;
reg START;
wire [6:0]LED_D;
wire [6:0]LED_C;
wire [6:0]LED_B;
wire [6:0]LED_A;
wire FULL;	
integer res_file;

initial
begin
	res_file = $fopen ("Results.txt");
	$fdisplay (res_file,"Inputs: F_INPUT START RESET F_PATTERN F_CONV\n");
	$fdisplay (res_file,"Outputs: LED_D LED_C LED_B LED_A\n");
end

initial	$fmonitor (res_file, "%d ps %b %b %b %b %b %b %b %b %b", $time,
						 F_INPUT, START, RESET, F_PATTERN, F_CONV,
						 LED_D, LED_C, LED_B, LED_A);

// Unit Under Test port map
	freq_m UUT (
		.F_CONV(F_CONV),
		.F_INPUT(F_INPUT),
		.F_PATTERN(F_PATTERN),
		.RESET(RESET),
		.START(START),
		.LED_D(LED_D),
		.LED_C(LED_C),
		.LED_B(LED_B),
		.LED_A(LED_A),
		.FULL(FULL));

initial
	$dumpvars (0,frequency_meter_tb);



initial
begin : STIMUL // begin of stimulus process
//# <time to next event> //<current time>
	#0
	RESET = 1'b1;
	START = 1'b0;
	$dumpflush;
	#8000000; //0
	RESET = 1'b0;
	$dumpflush;
	#24000000; //8000000
	START = 1'b1;
	$dumpflush;
	#198000000; //32000000
	START = 1'b0;
	$dumpflush;
	#120100000; //230000000
	$dumpflush;
	#200000; //350100000
	$finish;

//	end of stimulus events
end // end of stimulus process
	

always
begin : CLOCK_F_CONV
	//this process was generated based on formula: 0 0, 1 500000 -r 1000000
	//#<time to next event>; // <current time>
	F_CONV = 1'b0;
	$dumpflush;
	#500000; //0
	F_CONV = 1'b1;
	$dumpflush;
	#500000; //500000
end

always
begin : CLOCK_F_INPUT
	//this process was generated based on formula: 0 0, 1 285714 -r 571429
	//#<time to next event>; // <current time>
	F_INPUT = 1'b0;
	$dumpflush;
	#285714; //0
	F_INPUT = 1'b1;
	$dumpflush;
	#285715; //285714
end

always
begin : CLOCK_F_PATTERN
	//this process was generated based on formula: 0 0, 1 25000000 -r 50000000
	//#<time to next event>; // <current time>
	F_PATTERN = 1'b0;
	$dumpflush;
	#25000000; //0
	F_PATTERN = 1'b1;
	$dumpflush;
	#25000000; //25000000
end
endmodule
