alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/uut_std.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/uut_pli.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/dac_sc1.bde"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/lrc.bde"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/adrcnt.bde"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/datreg.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/sub.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/reg4.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/comp.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/dat_cnt.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/intelhex.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/asciidec.v"
alog -dbg -pli "$dsn/src/external/read_byte_ex.dll" "$dsn/src/cd4029.v"
comp "$dsn/src/external/read_byte_ex.dlm"
