acom -dbg "$dsn/src/and2.vhd"
acom -dbg "$dsn/src/cnt_4b.vhd"
acom -dbg "$dsn/src/hex2led.vhd"
acom -dbg "$dsn/src/cnt_bcd.bde"
acom -dbg "$dsn/src/control.asf"
acom -dbg "$dsn/src/freq_top.bde"
acom -dbg "$dsn/src/vhpi_component.vhd"
acom -dbg "$dsn/src/testbench/testbenchpack.vhd"
acom -dbg "$dsn/src/testbench/testbench_vhpi.vhd"
acom -dbg "$dsn/src/testbench_cnt_bcd_conf.vhd"
comp "$dsn/src/vhpi_for_ahdl/vhpi_for_ahdl.dlm"
